package com.ksxt.model;

import java.util.Date;

public class Danxuan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danxuan.id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danxuan.tk_id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Integer tkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danxuan.subject
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danxuan.image
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danxuan.option_a
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private String optionA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danxuan.option_b
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private String optionB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danxuan.option_c
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private String optionC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danxuan.option_d
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private String optionD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danxuan.answer
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danxuan.analysis
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private String analysis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danxuan.create_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danxuan.update_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danxuan.id
     *
     * @return the value of danxuan.id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danxuan.id
     *
     * @param id the value for danxuan.id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danxuan.tk_id
     *
     * @return the value of danxuan.tk_id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Integer getTkId() {
        return tkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danxuan.tk_id
     *
     * @param tkId the value for danxuan.tk_id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setTkId(Integer tkId) {
        this.tkId = tkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danxuan.subject
     *
     * @return the value of danxuan.subject
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danxuan.subject
     *
     * @param subject the value for danxuan.subject
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danxuan.image
     *
     * @return the value of danxuan.image
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danxuan.image
     *
     * @param image the value for danxuan.image
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danxuan.option_a
     *
     * @return the value of danxuan.option_a
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public String getOptionA() {
        return optionA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danxuan.option_a
     *
     * @param optionA the value for danxuan.option_a
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setOptionA(String optionA) {
        this.optionA = optionA == null ? null : optionA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danxuan.option_b
     *
     * @return the value of danxuan.option_b
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public String getOptionB() {
        return optionB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danxuan.option_b
     *
     * @param optionB the value for danxuan.option_b
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setOptionB(String optionB) {
        this.optionB = optionB == null ? null : optionB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danxuan.option_c
     *
     * @return the value of danxuan.option_c
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public String getOptionC() {
        return optionC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danxuan.option_c
     *
     * @param optionC the value for danxuan.option_c
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setOptionC(String optionC) {
        this.optionC = optionC == null ? null : optionC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danxuan.option_d
     *
     * @return the value of danxuan.option_d
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public String getOptionD() {
        return optionD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danxuan.option_d
     *
     * @param optionD the value for danxuan.option_d
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setOptionD(String optionD) {
        this.optionD = optionD == null ? null : optionD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danxuan.answer
     *
     * @return the value of danxuan.answer
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danxuan.answer
     *
     * @param answer the value for danxuan.answer
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danxuan.analysis
     *
     * @return the value of danxuan.analysis
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public String getAnalysis() {
        return analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danxuan.analysis
     *
     * @param analysis the value for danxuan.analysis
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis == null ? null : analysis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danxuan.create_date
     *
     * @return the value of danxuan.create_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danxuan.create_date
     *
     * @param createDate the value for danxuan.create_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danxuan.update_date
     *
     * @return the value of danxuan.update_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danxuan.update_date
     *
     * @param updateDate the value for danxuan.update_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}