package com.ksxt.model;

import java.util.Date;

public class Shiti {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiti.id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiti.sj_id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	private Long sjId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiti.tx_id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	private Integer txId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiti.tm_id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	private Long tmId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiti.score
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	private Float score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiti.next_id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	private Long nextId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiti.create_date
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shiti.update_date
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	private Date updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiti.id
	 * @return  the value of shiti.id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiti.id
	 * @param id  the value for shiti.id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiti.sj_id
	 * @return  the value of shiti.sj_id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public Long getSjId() {
		return sjId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiti.sj_id
	 * @param sjId  the value for shiti.sj_id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public void setSjId(Long sjId) {
		this.sjId = sjId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiti.tx_id
	 * @return  the value of shiti.tx_id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public Integer getTxId() {
		return txId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiti.tx_id
	 * @param txId  the value for shiti.tx_id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public void setTxId(Integer txId) {
		this.txId = txId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiti.tm_id
	 * @return  the value of shiti.tm_id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public Long getTmId() {
		return tmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiti.tm_id
	 * @param tmId  the value for shiti.tm_id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public void setTmId(Long tmId) {
		this.tmId = tmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiti.score
	 * @return  the value of shiti.score
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public Float getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiti.score
	 * @param score  the value for shiti.score
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public void setScore(Float score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiti.next_id
	 * @return  the value of shiti.next_id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public Long getNextId() {
		return nextId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiti.next_id
	 * @param nextId  the value for shiti.next_id
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public void setNextId(Long nextId) {
		this.nextId = nextId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiti.create_date
	 * @return  the value of shiti.create_date
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiti.create_date
	 * @param createDate  the value for shiti.create_date
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shiti.update_date
	 * @return  the value of shiti.update_date
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shiti.update_date
	 * @param updateDate  the value for shiti.update_date
	 * @mbggenerated  Thu Feb 16 16:12:35 CST 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
}