package com.ksxt.model;

import java.util.Date;

public class Anlifenxi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anlifenxi.id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anlifenxi.tk_id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Integer tkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anlifenxi.subject
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anlifenxi.image
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anlifenxi.create_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anlifenxi.update_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anlifenxi.id
     *
     * @return the value of anlifenxi.id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anlifenxi.id
     *
     * @param id the value for anlifenxi.id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anlifenxi.tk_id
     *
     * @return the value of anlifenxi.tk_id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Integer getTkId() {
        return tkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anlifenxi.tk_id
     *
     * @param tkId the value for anlifenxi.tk_id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setTkId(Integer tkId) {
        this.tkId = tkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anlifenxi.subject
     *
     * @return the value of anlifenxi.subject
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anlifenxi.subject
     *
     * @param subject the value for anlifenxi.subject
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anlifenxi.image
     *
     * @return the value of anlifenxi.image
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anlifenxi.image
     *
     * @param image the value for anlifenxi.image
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anlifenxi.create_date
     *
     * @return the value of anlifenxi.create_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anlifenxi.create_date
     *
     * @param createDate the value for anlifenxi.create_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anlifenxi.update_date
     *
     * @return the value of anlifenxi.update_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anlifenxi.update_date
     *
     * @param updateDate the value for anlifenxi.update_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}