package com.ksxt.model;

import java.util.Date;

public class JisuanfenxiSub {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jisuanfenxi_sub.id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jisuanfenxi_sub.jsfx_id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Long jsfxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jisuanfenxi_sub.answer
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jisuanfenxi_sub.order_id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jisuanfenxi_sub.analysis
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private String analysis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jisuanfenxi_sub.create_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jisuanfenxi_sub.update_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jisuanfenxi_sub.id
     *
     * @return the value of jisuanfenxi_sub.id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jisuanfenxi_sub.id
     *
     * @param id the value for jisuanfenxi_sub.id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jisuanfenxi_sub.jsfx_id
     *
     * @return the value of jisuanfenxi_sub.jsfx_id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Long getJsfxId() {
        return jsfxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jisuanfenxi_sub.jsfx_id
     *
     * @param jsfxId the value for jisuanfenxi_sub.jsfx_id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setJsfxId(Long jsfxId) {
        this.jsfxId = jsfxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jisuanfenxi_sub.answer
     *
     * @return the value of jisuanfenxi_sub.answer
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jisuanfenxi_sub.answer
     *
     * @param answer the value for jisuanfenxi_sub.answer
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jisuanfenxi_sub.order_id
     *
     * @return the value of jisuanfenxi_sub.order_id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jisuanfenxi_sub.order_id
     *
     * @param orderId the value for jisuanfenxi_sub.order_id
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jisuanfenxi_sub.analysis
     *
     * @return the value of jisuanfenxi_sub.analysis
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public String getAnalysis() {
        return analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jisuanfenxi_sub.analysis
     *
     * @param analysis the value for jisuanfenxi_sub.analysis
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis == null ? null : analysis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jisuanfenxi_sub.create_date
     *
     * @return the value of jisuanfenxi_sub.create_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jisuanfenxi_sub.create_date
     *
     * @param createDate the value for jisuanfenxi_sub.create_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jisuanfenxi_sub.update_date
     *
     * @return the value of jisuanfenxi_sub.update_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jisuanfenxi_sub.update_date
     *
     * @param updateDate the value for jisuanfenxi_sub.update_date
     *
     * @mbggenerated Sun Feb 12 19:00:46 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}