package com.ksxt.model;

import java.util.Date;

import com.ksxt.common.helper.KaoshiInfo;

public class KaoshiLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaoshi_log.uid
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	private Long uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaoshi_log.sj_id
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	private Long sjId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaoshi_log.st_id
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	private Long stId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaoshi_log.answer
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	private String answer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaoshi_log.score
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	private Float score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaoshi_log.version
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kaoshi_log.create_date
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaoshi_log.uid
	 * @return  the value of kaoshi_log.uid
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public Long getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaoshi_log.uid
	 * @param uid  the value for kaoshi_log.uid
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public void setUid(Long uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaoshi_log.sj_id
	 * @return  the value of kaoshi_log.sj_id
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public Long getSjId() {
		return sjId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaoshi_log.sj_id
	 * @param sjId  the value for kaoshi_log.sj_id
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public void setSjId(Long sjId) {
		this.sjId = sjId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaoshi_log.st_id
	 * @return  the value of kaoshi_log.st_id
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public Long getStId() {
		return stId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaoshi_log.st_id
	 * @param stId  the value for kaoshi_log.st_id
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public void setStId(Long stId) {
		this.stId = stId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaoshi_log.answer
	 * @return  the value of kaoshi_log.answer
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public String getAnswer() {
		return answer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaoshi_log.answer
	 * @param answer  the value for kaoshi_log.answer
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public void setAnswer(String answer) {
		this.answer = answer == null ? null : answer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaoshi_log.score
	 * @return  the value of kaoshi_log.score
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public Float getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaoshi_log.score
	 * @param score  the value for kaoshi_log.score
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public void setScore(Float score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaoshi_log.version
	 * @return  the value of kaoshi_log.version
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaoshi_log.version
	 * @param version  the value for kaoshi_log.version
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kaoshi_log.create_date
	 * @return  the value of kaoshi_log.create_date
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kaoshi_log.create_date
	 * @param createDate  the value for kaoshi_log.create_date
	 * @mbggenerated  Fri Feb 17 13:59:32 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
    public void fromInfo(KaoshiInfo info) {
        this.sjId = info.getSjId();
        this.stId = info.getStId();
        this.version = info.getVersion();
    }
}