package com.ksxt.model;

import java.util.Date;

public class KcTxRel extends KcTxRelKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kc_tx_rel.create_date
	 * @mbggenerated  Wed Feb 22 15:29:16 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kc_tx_rel.status
	 * @mbggenerated  Wed Feb 22 15:29:16 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column kc_tx_rel.update_date
	 * @mbggenerated  Wed Feb 22 15:29:16 CST 2017
	 */
	private Date updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kc_tx_rel.create_date
	 * @return  the value of kc_tx_rel.create_date
	 * @mbggenerated  Wed Feb 22 15:29:16 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kc_tx_rel.create_date
	 * @param createDate  the value for kc_tx_rel.create_date
	 * @mbggenerated  Wed Feb 22 15:29:16 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kc_tx_rel.status
	 * @return  the value of kc_tx_rel.status
	 * @mbggenerated  Wed Feb 22 15:29:16 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kc_tx_rel.status
	 * @param status  the value for kc_tx_rel.status
	 * @mbggenerated  Wed Feb 22 15:29:16 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column kc_tx_rel.update_date
	 * @return  the value of kc_tx_rel.update_date
	 * @mbggenerated  Wed Feb 22 15:29:16 CST 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column kc_tx_rel.update_date
	 * @param updateDate  the value for kc_tx_rel.update_date
	 * @mbggenerated  Wed Feb 22 15:29:16 CST 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
}